In [1]:
#https://www.youtube.com/watch?v=K796Ae4gLlY

In [2]:
#Why do we do dimensionality reduction
#reason 1 - space efficiency
#reason 2 - computing efficiency
#reason 3 - visualization (so we can analyze by human eye)

#We will build PCS and then compare it to T-SNE and LDA (3 DR methods in total)

In [8]:
import numpy as np #math
np.random.seed(1) #for debugging

In [9]:
#step 1 - Create your dataset

mu_vec1 = np.array([0,0,1]) #sample mean
cov_mat1 = np.array([[1,0,0],[0,1,0], [0,0,1]]) #sample covariance

class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20).T
print class1_sample

#What is happening here?
#A multi-variate normal distribution was generated; A Gaussian distributon

#3x20 matrix; 3 columns and 20 rows

[[ 1.62434536 -1.07296862  1.74481176 -0.24937038 -0.3224172  -1.09989127
   0.04221375  1.14472371  0.90085595 -0.93576943 -0.69166075 -0.84520564
  -1.11731035  0.74204416 -0.74715829 -0.63699565  0.12015895 -0.35224985
  -0.20889423  0.93110208]
 [-0.61175641  0.86540763 -0.7612069   1.46210794 -0.38405435 -0.17242821
   0.58281521  0.90159072 -0.68372786 -0.26788808 -0.39675353 -0.67124613
   0.2344157  -0.19183555  1.6924546   0.19091548  0.61720311 -1.1425182
   0.58662319  0.28558733]
 [ 0.47182825 -1.3015387   1.3190391  -1.06014071  2.13376944  0.12214158
  -0.10061918  1.50249434  0.87710977  1.53035547  0.3128273   0.9873354
   2.65980218  0.11237104  1.05080775  3.10025514  1.30017032  0.65065728
   1.83898341  1.88514116]]


In [10]:
#step 1 - Create your dataset

mu_vec2 = np.array([1,1,1]) #sample mean
cov_mat2 = np.array([[1,0,0],[0,1,0], [0,0,1]]) #sample covariance

class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20).T
print class2_sample

#What is happening here?
#A multi-variate normal distribution was generated; A Gaussian distributon

#3x20 matrix; 3 columns and 20 rows

[[ 0.24560206  0.70190716  2.13162939 -0.39649634  1.16003707 -1.02220122
   1.23009474  0.79924193  1.19829972  1.37756379  2.19891788  0.36126959
   0.65614632  1.69803203  1.40349164  1.16938243  0.73378149  1.31515939
   1.35054598 -0.61577235]
 [ 2.25286816  1.48851815  2.51981682 -0.44411381  1.87616892  0.69379599
   1.76201118  1.18656139  1.11900865  1.12182127  1.18515642  1.42349435
   1.04359686  0.55287144  1.59357852  1.74055645  1.03261455  1.84616065
  -0.31228341  2.12141771]
 [ 1.51292982  0.92442829  3.18557541  0.49553414  1.31563495  1.82797464
   0.77767186  1.41005165  0.32933771  2.12948391  0.62471505  1.07734007
   0.37999916  2.2245077  -0.09491185  0.0462994  -0.37311732  0.14048406
   0.96130449  1.40890054]]


In [17]:
%pylab inline

#step - 2 : plot the data
from matplotlib import pyplot as plt

#figure, width and height
fig = plt.figure(figsize=(8,8))
#3d subplot
#these are the subplot grid parameters encoded as a single integer,1x1 grid, 1srt subplot
ax = fig.add_subplot(111, projection='3d')
#fontsize
plt.rcParams['legend.fontsize'] = 10

#plot samples
ax.plot(class1_sample[0,:], class1_sample[1,:], class1_sample[2,:],
        'o', markersize=8, color='blue', alpha=0.5, label='class1')
ax.plot(class2_sample[0,:], class2_sample[1,:], class2_sample[2,:],
        '^', markersize=8, alpha=0.5, color='green', label='class2')

ax.legend(loc = 'upper right')

plt.show()

Populating the interactive namespace from numpy and matplotlib


ValueError: Unknown projection '3d'

In [ ]:
#Step 3 - Merge the data into one bigASS dataset

In [19]:
all_sample = np.concatenate((class1_sample, class2_sample), axis=1)

In [20]:
all_sample

array([[ 1.62434536, -1.07296862,  1.74481176, -0.24937038, -0.3224172 ,
        -1.09989127,  0.04221375,  1.14472371,  0.90085595, -0.93576943,
        -0.69166075, -0.84520564, -1.11731035,  0.74204416, -0.74715829,
        -0.63699565,  0.12015895, -0.35224985, -0.20889423,  0.93110208,
         0.24560206,  0.70190716,  2.13162939, -0.39649634,  1.16003707,
        -1.02220122,  1.23009474,  0.79924193,  1.19829972,  1.37756379,
         2.19891788,  0.36126959,  0.65614632,  1.69803203,  1.40349164,
         1.16938243,  0.73378149,  1.31515939,  1.35054598, -0.61577235],
       [-0.61175641,  0.86540763, -0.7612069 ,  1.46210794, -0.38405435,
        -0.17242821,  0.58281521,  0.90159072, -0.68372786, -0.26788808,
        -0.39675353, -0.67124613,  0.2344157 , -0.19183555,  1.6924546 ,
         0.19091548,  0.61720311, -1.1425182 ,  0.58662319,  0.28558733,
         2.25286816,  1.48851815,  2.51981682, -0.44411381,  1.87616892,
         0.69379599,  1.76201118,  1.18656139,  1.

In [22]:
all_sample.T

array([[ 1.62434536, -0.61175641,  0.47182825],
       [-1.07296862,  0.86540763, -1.3015387 ],
       [ 1.74481176, -0.7612069 ,  1.3190391 ],
       [-0.24937038,  1.46210794, -1.06014071],
       [-0.3224172 , -0.38405435,  2.13376944],
       [-1.09989127, -0.17242821,  0.12214158],
       [ 0.04221375,  0.58281521, -0.10061918],
       [ 1.14472371,  0.90159072,  1.50249434],
       [ 0.90085595, -0.68372786,  0.87710977],
       [-0.93576943, -0.26788808,  1.53035547],
       [-0.69166075, -0.39675353,  0.3128273 ],
       [-0.84520564, -0.67124613,  0.9873354 ],
       [-1.11731035,  0.2344157 ,  2.65980218],
       [ 0.74204416, -0.19183555,  0.11237104],
       [-0.74715829,  1.6924546 ,  1.05080775],
       [-0.63699565,  0.19091548,  3.10025514],
       [ 0.12015895,  0.61720311,  1.30017032],
       [-0.35224985, -1.1425182 ,  0.65065728],
       [-0.20889423,  0.58662319,  1.83898341],
       [ 0.93110208,  0.28558733,  1.88514116],
       [ 0.24560206,  2.25286816,  1.512

In [ ]:
#Step 4 - compute the dimensional mean vector, it will help compute the covariance matrix
#mean for each feature

In [44]:
mean_x = np.mean(all_sample[0,:])
mean_y = np.mean(all_sample[1,:])
mean_z = np.mean(all_sample[2,:])

#3d mean vector
mean_vector = np.array(([mean_x], [mean_y], [mean_z]))
print mean_vector

[[ 0.41667492]
 [ 0.69848315]
 [ 0.99242335]]


In [47]:
#Step5 - Compute covariance matrix
cov_mat = np.zeros((3,3))

for i in range((all_samples.shape[1])):
    cov_mat += (all_samples[:,i].reshape(3,1) - mean_vector).dot((all_samples[:,i].reshape(3,1)
print('Covariance Matrix:\n', cov_mat)

SyntaxError: invalid syntax (<ipython-input-47-31269ff9a6a6>, line 6)